ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    path('post/', views.PostLV.as_view(), name='post_list'),

    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),

    path('archive/<int:year>', views.PostYAV.as_view(), name='post_year_archive'),

    path('archive/<int:year>/<str:month>', views.PostMAV.as_view(), name='post_month_archive'),

    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),

    path('archive/today', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

ch99/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV, BookmarkDV

app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

]

ch99/blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

ch99/bookmark/models.py
from django.db import models


class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title

ch99/blog/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post


class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'


class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'


class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

ch99/bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

ch99/mysite/views.py
from django.views.generic import TemplateView


# --- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

ch99/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %} post_all.html{% endblock %}

{% block content %}
<h1>Blog List</h1>

{% for post in posts %}
  <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
  {{ post.modify_dt|date:"N d, Y" }}
  <p>{{ post.description }}</p>
{% endfor %}

<br>

<div>
  <span>
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
    {% endif %}

    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
    {% endif %}
  </span>
</div>
{% endblock %}

ch99/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}

<h1>Post Archives until {% now "N d, Y" %}</h1>

    {% for date in date_list %}
    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}"
    class="btn btn-outline-primary btn-sm mx-1">
        Year-{{ date|date:"Y"  }} </a>
    {% endfor %}

    <br><br>

<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

ch99/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}

    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a> </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

ch99/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}

    <h1>Post Archives for {{ month|date:"N, Y" }}</h1>
    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a> </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

ch99/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}

    <h1>Post Archives for {{ year|date:"Y" }}</h1>

    {% for date in date_list %}
    <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}"
        class="btn btn-outline-primary btn-sm mx-1">
        {{ date|date:"F" }}</a>
    {% endfor %}

    <br><br>

<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a> </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

ch99/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>

<p>
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
        <i class="fas fa-arrow-circle-left"></i> {{ object.get_previous }}
    </a>
    {% endif %}

    {% if object.get_next %}
    | <a href="{{ object.get_next.get_absolute_url }}" title="View next Post">
    {{ object.get_next }} <i class="fas fa-arrow-circle-right"></i>
    </a>
    {% endif %}
</p>

<p>{{ object.modify_dt|date:"j F Y" }}</p>
    <br>

<div>
    {{ object.content|linebreaks }}
</div>

<br>
<div>
    <b>TAGS</b> <i class="fas fa-tag"></i>
    {% load taggit_templatetags2_tags %}
    {% for tag in tags %}
    <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
    {% endfor %}
    &emsp;
    <a href="{% url 'blog:tag_cloud' %}"> <span class="btn btn-info btn-sm">TagCloud</span></a>
</div>
{% endblock %}

ch99/blog/templates/taggit/taggit_cloud.html
{% extends "base.html" %}

{% block title %}taggit_cloud.html{% endblock %}

{% block extra-style %}
<style type="text/css">
    .tag-cloud {
        width: 40%;
        margin-left: 30px;
        text-align: center;
        padding: 5px;
        border: 1px solid orange;
        background-color: #ffc;
    }
    .tag-1 {font-size: 12px;}
    .tag-2 {font-size: 14px;}
    .tag-3 {font-size: 16px;}
    .tag-4 {font-size: 18px;}
    .tag-5 {font-size: 20px;}
    .tag-6 {font-size: 24px;}
</style>
{% endblock %}

{% block content %}
    <h1>Blog Tag Cloud</h1>
    <br>

    <div class="tag-cloud">
        {% load taggit_templatetags2_tags %}
        {% get_tagcloud as tags %}
        {% for tag in tags %}
        <span class="tag-{{tag.weight|floatformat:0}}">
            <a href="{% url 'blog:tagged_object_list' tag.name %}"> {{tag.name}}({{tag.num_times}})</a>
        </span>
        {% endfor %}}
    </div>

{% endblock %}

ch99/blog/templates/taggit/taggit_post_list.html
{% extends "base.html" %}

{% block title %}taggit_post_list.html{% endblock %}

{% block content %}

<h1>Post for tag - {{ tagname }}</h1>
    <br>

{% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_dt|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

{% endblock %}

ch99/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}bookmark_detail.html{% endblock %}

{% block content %}
    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
{% endblock %}}

ch99/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}bookmark_list.html{% endblock %}

{% block content %}
    <hl>Bookmark List</hl>
    <br>

    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}}

ch99/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <div class="container-fluid">
    <span class="navbar-brand mx-5 mb-0 fw-bolder fst-italic">Django - Python Web Programming</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="">Photo</a>
        </li>
        <li class="nav-item dropdown mx-1 btn btn-primary">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Util
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="">Search</a></li>
          </ul>
        </li>
      </ul>
      <form class="form-inline my-2 mx-3" action="" method="post"> {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
      </form>
    </div>
  </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/11a7e3b59f.js" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

ch99/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
  .home-image {
    background-image: url("{% static 'img/ice.jpg' %}");
    background-repeat: no-repeat;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
  }
  .title {
    color: #c80;
    font-weight: bold;
  }
  .powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
  }
</style>
{% endblock %}

{% block content %}
<div class="home-image">
  <h2 class="title">Django - Python Web Programming</h2>
  <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
</div>

  <hr style="margin: 10px 0;">

  <div class="row text-center">
    <div class="col-sm-6">
      <h3>Bookmark App</h3>
      <p>Bookmark is a Uniform Resource Identifier (URI)
        that is stored for later retrieval in any of various storage formats.
      You can store your own bookmarks by Bookmark application.
      It's also possible to update or delete your bookmarks.</p>
    </div>
    <div class="col-sm-6">
      <h3>Blog App</h3>
      <p>This application makes it possible to log daily events or write your own interests
      such as hobbies, techniques, etc.
      A typical blog combines text, digital images, and links to other blogs, web pages, and other media related to its topic.</p>
    </div>
  </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
  <div class="text-white fst-italic text-end me-5">Copyright &copy; 2019 DjangoBook by shkim</div>
</footer>
{% endblock %}